TESTING = True

SQLALCHEMY_DATABASE_URI = 'sqlite:///database.sq3'
SQLALCHEMY_TRACK_MODIFICATIONS = False

GOOGLE_CLOUD_STORAGE_ACCESS_KEY = 'GOOGSONI473MFIBEURSAZ37Y'
GOOGLE_CLOUD_STORAGE_SECRET_KEY = 'ecXWcqar6ivF0FsBYtpyfp3Us34yeZSClSzmc5px'
GOOGLE_CLOUD_STORAGE_BUCKET = 'artshackstorageservice'
